---

- name: Install system-level requirements.
  become: 'yes'
  apt:
    update_cache: 'yes'
    name: "{{ django_system_packages }} + {{ django_system_packages_extra }}"
  tags:
    - requirements

- name: Create user for Django.
  user: name={{ django_user }}
        home="/home/{{ django_user }}"

- name: Create the project directory.
  become: 'yes'
  file: state=directory
        path={{ django_project_path }}
        owner={{ django_user }}
        group={{ django_user }}

- name: Check for symlink
  stat: path={{ django_deployment_symlink }}
  register: symlink

- name: Create Deployment Symlink
  file: src={{ django_project_path }}
        dest={{ django_deployment_symlink }}
        owner={{ django_user }}
        group={{ django_user }}
        force='yes'
        state=link
  when: not symlink.stat.exists

- name: Pull code from git repo.
  become: 'yes'
  become_user: '{{ django_user }}'
  git: repo={{ django_repo }}
       dest={{ django_project_source }}
       accept_hostkey='yes'
       key_file={{ django_deploy_key|default(omit) }}
       version={{ django_branch }}
  tags:
    - git

- name: Install Latest Pip+Setuptools
  pip: name={{ item.name }}
       version={{ item.version }}
       virtualenv={{ django_project_path }}
  with_items:
    - name: pip
      version: 20.0.2
    - name: setuptools
      version: 44.0.0

- name: Install python requirements
  pip: name={{ item }}
       state=present
       virtualenv={{ django_project_path }}
  with_items: '{{ django_python_requirements }}'

- name: Install python requirements file.
  pip: requirements={{ django_project_source }}/{{ django_requirements_file }}
       virtualenv={{ django_project_path }}
       state=present

- name: Configure Python PATH
  template: src=django.pth
            dest={{ django_project_path }}/lib/python{{ django_python_version }}/site-packages/

- name: Logging directory permissions
  become: 'yes'
  file: state=directory
        path=/var/log/uwsgi
        owner={{ django_user }}
        group={{ django_user }}
        recurse='yes'

- name: Virtualenv directory permissions
  become: 'yes'
  file: state=directory
        path={{ django_project_path }}
        owner={{ django_user }}
        group={{ django_user }}
        recurse='yes'

- name: Syncdb
  become: 'yes'
  become_user: '{{ django_user }}'
  django_manage: command=syncdb
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: '{{ django_env }}'
  when: django_syncdb

- name: Run Migrations.
  become: 'yes'
  become_user: '{{ django_user }}'
  django_manage: command=migrate
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: '{{ django_env }}'
  when: django_migrate

- name: Load Fixtures.
  become: 'yes'
  become_user: '{{ django_user }}'
  django_manage: command=loaddata
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
                 fixtures="{{ django_fixtures | join(" ") }}"
  environment: '{{ django_env }}'
  when: django_fixtures

- include: front_end.yml
  when: django_setup_frontend

- name: Move Deployment Symlink
  file: src={{ django_project_path }}
        dest={{ django_deployment_symlink }}
        owner={{ django_user }}
        group={{ django_user }}
        force='yes'
        state=link
  tags:
    - deploy

- name: Reload uWSGI process
  become: yes
  service: name={{ django_project_name }} state=reloaded
  when: ansible_distribution_release == 'trusty'

- name: Reload uWSGI process [systemd]
  become: yes
  systemd:
    name: '{{ django_project_name }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_distribution_release == 'bionic' or
        ansible_distribution_release == 'xenial'

- name: Run Post-Deploy script
  django_manage: command='runscript {{ item }}'
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: '{{ django_env }}'
  with_items: '{{ django_post_deploy_scripts }}'
  tags:
    - deploy
    - post_deploy_script
